apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: java-github-tekton-2611 
  janus-idp.io/tekton: java-github-tekton-2611
  backstage.io/kubernetes-id: java-github-tekton-2611
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: java-github-tekton-2611
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  